### ISSUE TITLE
[Gulp] ReferenceError: internalBinding is not defined

### ISSUE THREAD

**Issue by wallon-ines** [Drupal-FR/site-drupalfr#224]
La commande Gulp sort une erreur

```root@ce997eef5b72:/project/www/themes/custom/drupal_france# gulp watch:css
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/project/www/themes/custom/drupal_france/node_modules/natives/index.js:137:5)
    at require (/project/www/themes/custom/drupal_france/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/project/www/themes/custom/drupal_france/node_modules/natives/index.js:137:5)
    at require (/project/www/themes/custom/drupal_france/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/project/www/themes/custom/drupal_france/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/project/www/themes/custom/drupal_france/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/project/www/themes/custom/drupal_france/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
```
Pour corriger le problème, il faut faire :
```npm install natives@1.1.6```
Source:
https://github.com/gulpjs/gulp/issues/2246#issuecomment-435646661

**Comment by FlorentTorregrosa** [comment]
À cause de gulp 4 qui doit être téléchargé et le gulpfile.js qui doit avoir une syntaxe pour gulp 3 je pense.
