### ISSUE TITLE
Problème installation via Composer

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#32]
Salut @FlorentTorregrosa 
Bien motivé à faire un peu de code cet après midi, je me mets à jour pour reprendre tout ton travail (super, merci d'ailleurs).

Mon parcours : 
```
git checkout 8.x-1.x 
git pull --rebase origin 8.x-1.x
docker-compose pull
docker-compose up
docker-compose exec web /bin/bash
root@0d92d824e637:/project/www# cd ..
root@0d92d824e637:/project# ./scripts/install.sh
```

Bon, là, j'ai plusieurs warning, mais je pense que tu es au courant et que ce n'est pas critique.

```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
``` 

```
Warning: Ambiguous class resolution, "Drupal\Component\Utility\Random" was found in both "$baseDir . '/www/core/lib/Drupal/Component/Utility/Random.php" and "/project/vendor/drupal/drupal-driver/src/Drupal/Component/Utility/Random.php", the first will be used.
```

Et plusieurs erreurs : 

```
[error]  Mailchimp Error: API Key cannot be blank. 
[error]  An error occurred requesting memberinfo for example@example.com in list 26bff72b56. "Cannot get member info without MailChimp API. Check API key has been entered." 
```

[error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 

Plusieurs fois (je ne pense pas que cela soit très grave)
Mais surtout : 

```
[error]  Error: Cannot use object of type Closure as array in Drupal\webprofiler\EventDispatcher\TraceableEventDispatcher->addCalledListener() (line 174 of /project/www/modules/contrib/devel/webprofiler/src/EventDispatcher/TraceableEventDispatcher.php) #0 /project/www/modules/contrib/devel/webprofiler/src/EventDispatcher/TraceableEventDispatcher.php(78): Drupal\webprofiler\EventDispatcher\TraceableEventDispatcher->addCalledListener(Array, 'feeds.fetch', 0)
#1 /project/www/modules/contrib/feeds/src/Event/EventDispatcherTrait.php(37): Drupal\webprofiler\EventDispatcher\TraceableEventDispatcher->dispatch('feeds.fetch', Object(Drupal\feeds\Event\FetchEvent))
#2 /project/www/modules/contrib/feeds/src/Plugin/QueueWorker/FeedRefresh.php(137): Drupal\feeds\Plugin\QueueWorker\FeedQueueWorkerBase->dispatchEvent('feeds.fetch', Object(Drupal\feeds\Event\FetchEvent))
#3 /project/www/modules/contrib/feeds/src/Plugin/QueueWorker/FeedRefresh.php(77): Drupal\feeds\Plugin\QueueWorker\FeedRefresh->import(Object(Drupal\feeds\Entity\Feed), 'begin')
#4 /project/www/core/lib/Drupal/Core/Cron.php(167): Drupal\feeds\Plugin\QueueWorker\FeedRefresh->processItem(Array)
#5 /project/www/core/lib/Drupal/Core/Cron.php(133): Drupal\Core\Cron->processQueues()
#6 /project/www/core/lib/Drupal/Core/ProxyClass/Cron.php(75): Drupal\Core\Cron->run()
#7 /project/vendor/drush/drush/src/Drupal/Commands/core/DrupalCommands.php(61): Drupal\Core\ProxyClass\Cron->run()
#8 [internal function]: Drush\Drupal\Commands\core\DrupalCommands->cron(Array)
#9 /project/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)
#10 /project/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#11 /project/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#12 /project/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#13 /project/vendor/symfony/console/Command/Command.php(264): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /project/vendor/symfony/console/Application.php(859): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /project/vendor/symfony/console/Application.php(206): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /project/vendor/symfony/console/Application.php(125): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /project/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /project/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\Runtime\Runtime->doRun(Array)
#19 /project/vendor/drush/drush/drush.php(64): Drush\Runtime\Runtime->run(Array)
#20 /project/vendor/drush/drush/drush(4): require('/project/vendor...')
#21 {main}. 
```
deux fois, suivi de 

```
Error: Cannot use object of type Closure as array in Drupal\webprofiler\EventDispatcher\TraceableEventDispatcher->addCalledListener() (line 174 of /project/www/modules/contrib/devel/webprofiler/src/EventDispatcher/TraceableEventDispatcher.php).
```
et
```
[error]  Drush command terminated abnormally due to an unrecoverable error. 
```

Le site affiche bien la home page, mais une fois que je désire m'identifier, j'ai ce message en bas de page : 

```
The website encountered an unexpected error. Please try again later.
RuntimeException: Unable to create the storage directory (/project/www/sites/default/files/profiler/d8/b3). in Symfony\Component\HttpKernel\Profiler\FileProfilerStorage->write() (line 141 of /project/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php).

Symfony\Component\HttpKernel\Profiler\FileProfilerStorage->write(Object) (Line: 120)
Symfony\Component\HttpKernel\Profiler\Profiler->saveProfile(Object) (Line: 120)
Symfony\Component\HttpKernel\EventListener\ProfilerListener->onKernelTerminate(Object, 'kernel.terminate', Object) (Line: 76)
Drupal\webprofiler\EventDispatcher\TraceableEventDispatcher->dispatch('kernel.terminate', Object) (Line: 88)
Symfony\Component\HttpKernel\HttpKernel->terminate(Object, Object) (Line: 32)
Stack\StackedHttpKernel->terminate(Object, Object) (Line: 635)
Drupal\Core\DrupalKernel->terminate(Object, Object) (Line: 22)
```

J'ai naivement voulu chown le projet... mauvaise idée...
Ce n'est pas pour le moment bloquant, mais bon, je te remonte l'info.

**Comment by FlorentTorregrosa** [comment]
Salut @FlorisMoriceau,

Merci pour ton retour.
Pour moi c'est le bon parcours / les bonnes commandes que tu as faites.

```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
``` 
En effet, pas important, c'est dû au fait qu'on se connecte au conteneur en tant que root.

```
Warning: Ambiguous class resolution, "Drupal\Component\Utility\Random" was found in both "$baseDir . '/www/core/lib/Drupal/Component/Utility/Random.php" and "/project/vendor/drupal/drupal-driver/src/Drupal/Component/Utility/Random.php", the first will be used.
```
J'ai refait la manip pour vérifier, j'ai aussi le même warning, je ne me rendais même plus compte que je l'avais, et oui ce n'est pas grave.
```
[error]  Mailchimp Error: API Key cannot be blank. 
[error]  An error occurred requesting memberinfo for example@example.com in list 26bff72b56. "Cannot get member info without MailChimp API. Check API key has been entered." 
```
C'est dans l'import migrate des utilisateurs de test, le module Mailchimp doit réagir à la création des entité user pour voir s'ils sont dans des listes Mailchimp, sauf qu'il lui faut une clé API et même avec, tu aurais des warning car on n'a pas d'user avec les adresses mail example@exemple.org :).
Donc oui, pas d'inquiétude.
```
[error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
```
Ça c'est search api => #30
```
[error]  Error: Cannot use object of type Closure as array in Drupal\webprofiler\EventDispatcher\TraceableEventDispatcher->addCalledListener() (line 174 of /project/www/modules/contrib/devel/webprofiler/src/EventDispatcher/TraceableEventDispatcher.php) #0 /project/www/modules/contrib/devel/webprofiler/src/EventDispatcher/TraceableEventDispatcher.php(78): Drupal\webprofiler\EventDispatcher\TraceableEventDispatcher->addCalledListener(Array, 'feeds.fetch', 0)
#1 /project/www/modules/contrib/feeds/src/Event/EventDispatcherTrait.php(37): Drupal\webprofiler\EventDispatcher\TraceableEventDispatcher->dispatch('feeds.fetch', Object(Drupal\feeds\Event\FetchEvent))
#2 /project/www/modules/contrib/feeds/src/Plugin/QueueWorker/FeedRefresh.php(137): Drupal\feeds\Plugin\QueueWorker\FeedQueueWorkerBase->dispatchEvent('feeds.fetch', Object(Drupal\feeds\Event\FetchEvent))
#3 /project/www/modules/contrib/feeds/src/Plugin/QueueWorker/FeedRefresh.php(77): Drupal\feeds\Plugin\QueueWorker\FeedRefresh->import(Object(Drupal\feeds\Entity\Feed), 'begin')
#4 /project/www/core/lib/Drupal/Core/Cron.php(167): Drupal\feeds\Plugin\QueueWorker\FeedRefresh->processItem(Array)
#5 /project/www/core/lib/Drupal/Core/Cron.php(133): Drupal\Core\Cron->processQueues()
#6 /project/www/core/lib/Drupal/Core/ProxyClass/Cron.php(75): Drupal\Core\Cron->run()
#7 /project/vendor/drush/drush/src/Drupal/Commands/core/DrupalCommands.php(61): Drupal\Core\ProxyClass\Cron->run()
#8 [internal function]: Drush\Drupal\Commands\core\DrupalCommands->cron(Array)
#9 /project/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)
#10 /project/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#11 /project/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#12 /project/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#13 /project/vendor/symfony/console/Command/Command.php(264): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /project/vendor/symfony/console/Application.php(859): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /project/vendor/symfony/console/Application.php(206): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /project/vendor/symfony/console/Application.php(125): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /project/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /project/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\Runtime\Runtime->doRun(Array)
#19 /project/vendor/drush/drush/drush.php(64): Drush\Runtime\Runtime->run(Array)
#20 /project/vendor/drush/drush/drush(4): require('/project/vendor...')
#21 {main}. 
```
Ça c'est Webprofiler et Feeds qui ne s'entende pas bien lors de l'import dans le cron => #28
Si ça devient gênant, je pense qu'on désactivera Webprofiler même en développement.
```
[error]  Drush command terminated abnormally due to an unrecoverable error. 
```
C'est l'erreur précédente qui fait s'interrompre la commande Drush cron dans le script d'install.
```
The website encountered an unexpected error. Please try again later.
RuntimeException: Unable to create the storage directory (/project/www/sites/default/files/profiler/d8/b3). in Symfony\Component\HttpKernel\Profiler\FileProfilerStorage->write() (line 141 of /project/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php).

Symfony\Component\HttpKernel\Profiler\FileProfilerStorage->write(Object) (Line: 120)
Symfony\Component\HttpKernel\Profiler\Profiler->saveProfile(Object) (Line: 120)
Symfony\Component\HttpKernel\EventListener\ProfilerListener->onKernelTerminate(Object, 'kernel.terminate', Object) (Line: 76)
Drupal\webprofiler\EventDispatcher\TraceableEventDispatcher->dispatch('kernel.terminate', Object) (Line: 88)
Symfony\Component\HttpKernel\HttpKernel->terminate(Object, Object) (Line: 32)
Stack\StackedHttpKernel->terminate(Object, Object) (Line: 635)
Drupal\Core\DrupalKernel->terminate(Object, Object) (Line: 22)
```
Hum celle là je l'ai pas quand je navigue sur le site.
Pour les problèmes de droits de fichier dans Docker, si le répertoire /project/www/sites/default/files, t'embête pas, fait un chmod 777.
Pour les fichiers non versionnés comme le core ou les modules contrib, si tu dois faire des modifs le temps de faire du debug, tu peux faire pareil, un chmod 777.
Sinon ce qui est possible de faire, une fois connecté dans le conteneur, tu fais un "ll /project" (c'est un ls -l) pour lister les fichiers avec les droits. Et tu devrais voir des fichiers qui n'appartiennent pas à root dû au montage de volumes entre fichiers sur la machine / fichiers dans le conteneur.
Et par exemple sur ma machine ça me donne des fichiers avec l'utilisateur 1000 et le groupe 1000. Il y a des chances que ce ne soit pas le même ID utilisateur, mais c'est possible alors dans le conteneur de faire un "chown 1000:1000 -R /project/core /project/ce_que_tu_as_besoin" pour avoir les fichiers éditables depuis ta machine sans avoir besoin de chmod 777. J'en fais régulièrement après l'export de conf, vu que la commande réassigne tous les fichiers de conf à root:root.

Dis moi si ça t'éclaire et te permet d'être ok :)

**Comment by FlorisMoriceau** [comment]
Salut Florent, 
Merci pour toutes tes réponses.

Bon, j'ai CHMODé le dossier sites/default/files en 777.
C'est moche, mais je n'ai plus de problèmes à ce niveau là. 💛 

Je ferme le ticket, ou on le garde tant que les warning ne sont pas résolus ?

**Comment by FlorentTorregrosa** [comment]
Salut Floris,

Ok, cool que ça marche.

On peut fermer le ticket puisque les problème contrib ont leur issue dédiée. Si pour les autres warning quelqu'un d'autre repose la question, je créerai une page de wiki.
